<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Example 1</title>
    {!! Html::style('/admin/pdf/style.css') !!}

</head>
<body>

<main>
    <header class="clearfix">
        <div id="logo">
            <img src="{{ asset('/admin/pdf/logo.png') }}">
        </div>
        <h1>INFORME {{$date}}</h1>

        <div id="company" class="clearfix">
            <div>Souciones Informaticas</div>
            <div>605 sw 24 ave,<br/> Miami FL , 33135</div>
            <div>(305) 319-0148</div>
            <div><a href="mailto:dennyrock18@gmail.com">admin@demo.com</a></div>
        </div>
    </header>
</main>

@yield('content')

<footer>
    Invoice was created on a computer and is valid without the signature and seal.
    <br>
    Generated by: {{auth()->user()->fullname}}
</footer>

</body>
</html>


